install_ios:
    cargo install cargo-lipo
    cargo install cbindgen
    rustup target add aarch64-apple-ios	
    rustup target add x86_64-apple-ios
    rustup target add aarch64-apple-ios-sim	

install_window: 
    rustup target add x86_64-pc-windows-gnu
    rustup target add x86_64-pc-windows-msvc 

install_android:
    cargo install cargo-ndk
    rustup target add \
        aarch64-linux-android \
        armv7-linux-androideabi \
        x86_64-linux-android \
        i686-linux-android
    
install_macos:
    cargo install cargo-lipo
    cargo install cbindgen
    rustup target add x86_64-apple-darwin
    rustup target add aarch64-apple-darwin

lipo_build:
  cargo lipo --release

macos_build:
    cargo lipo --manifest-path Cargo.toml --targets x86_64-apple-darwin --release
ios_build:
    cargo lipo --manifest-path Cargo.toml --targets x86_64-apple-ios,aarch64-apple-ios	 --release
android_build:
    cargo install cargo-ndk
    rustup target add \
        aarch64-linux-android \
        armv7-linux-androideabi \
        x86_64-linux-android \
        i686-linux-android
    cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o ../android/app/src/main/jniLibs build
android_no_simulator:
    cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -o ../android/app/src/main/jniLibs build


ios_ci_cd:
  just install_ios
  just ios_build
  cp ../target/universal/release/libnative.a  ../ios
macos_ci_cd:
  just install_macos
  just macos_build
  cp  target/x86_64-apple-darwin/release/libnative.a    ../macos
  cp  target/x86_64-apple-darwin/release/libnative.dylib ../macos
